### ISSUE TITLE
Copy master image for preview deploys

### ISSUE THREAD

**Issue by jayvdb** [netlify/build-image#103]
Preview deploys can take a long time to build during the "Deploying to CDN" phase, as they start from an empty site.  In my case there are ~2500 files, and it takes >5mins even if only a few files are modified.

The image use for the build could be master image (or another one from a more recent commit on the build's branch), needing fewer files to be uploaded.

Also potentially, for some builds there are no files modified, and Netlify could skip the preview build publishing, because it is the same as a previous published build.

https://serverfault.com/questions/349460/how-to-move-files-between-two-s3-buckets-with-minimum-cost
(also much quicker)

**Comment by rybit** [comment]
Interesting! The deploy process has little to do with the image we use. This just serves as the basis for what we build in. 

Deploying a lot of files (I know, 2500 isn't that many) is a pain point we are trying to address. The process is cumbersome because we send a list of SHAs of all the files in the deploy (sooo ~2500 for you) and then we have to sort and figure what ones actually need to be uploaded. In this process we dedup across deploys, meaning your preview shouldn't be anymore susceptible to _deploy_ failures (there are other stages that are...). Meaning, that if you only change 5 files - we only try to upload those. There are some definite pitfalls along this way.

I'd recommend writing into support if you're having a lot of build issues, we can try to address them better there.
