### ISSUE TITLE
Release timing?

### ISSUE THREAD

**Issue by mortenson** [netlify/build-image#181]
Hey there - I was just wondering what the release cycle is for this project, and when changes to the build here will be reflected on the Netlify platform.

Not trying to push anyone to do a release soon, just would be good to know so I don't have to keep triggering my builds to find out if the image is updated.

Thanks!

**Comment by rybit** [comment]
Hi! Sorry there is no formal release timing. I can notify here and look into making a more reliable way to notify when things are rolled out (like making a release here).

**Comment by fool** [comment]
The normal maintainer of this repo is @brycekahle and he tries very hard to update the [CHANGELOG](https://github.com/netlify/build-image/blob/master/CHANGELOG.md) with any customer-facing changes, though that will just indicate this code changing rather than rolled out to the build network.  That roll-out *tends* to happen fairly quickly after releases...

**Comment by brycekahle** [comment]
@mortenson `2.4.2` just went out with your change.
