### ISSUE TITLE
Switch to 1.11 for Golang

### ISSUE THREAD

**Issue by zet4** [netlify/build-image#206]
Go 1.11 has been released quite a while ago and Netlify still uses 1.10 in it's build images.
Ideally of course `gimme stable` should be used, since that will always default to the most stable latest Go version.

**Comment by bcomnes** [comment]
Agreed! We'll get this bumped soon.

**Comment by ddevault** [comment]
Go 1.14 is out... a year and a half later.

**Comment by mraerino** [comment]
you can use any Go version via `GO_VERSION`. We're updating the main tools periodically.

**Comment by ddevault** [comment]
With a period of a year and a half, apparently. And longer for the Ubuntu image :)

**Comment by mraerino** [comment]
Using `GO_VERSION` was possible for a long time and is the recommended approach.

Netlify currently only has Ubuntu images:
- Trusty
  - End of life
  - no longer supported
- Xenial
  - latest updates
  - default if you create a new site
  - for old sites you can switch in the build settings

Our main goal has always been to not break user's build unexpectedly, that's the reason, you need to manually update the version instead of us doing it for you.

If you have any more questions please head over to https://community.netlify.com/
