### ISSUE TITLE
add Yarn to build-image

### ISSUE THREAD

**Issue by fool** [netlify/build-image#25]
https://github.com/yarnpkg/yarn

**Comment by fool** [comment]
while you're in there, it would be awesome to get #24 and #22 handled as well @rybit  :)

**Comment by t-richards** [comment]
Arguably, the most important feature of `yarn` is that it installs dependencies over 9000% faster than `npm`. Unfortunately, due to the fact that `npm install` is run automatically by `run-build.sh`, it kind of defeats the purpose of having `yarn` available in the first place, IMO.

It would be nice to have some way to opt-out of this default behavior. Maybe an environment variable `SKIP_NPM=true` that would tell `run-build.sh` to skip the `npm install` portion of the script.

I'd be happy to write up a PR if you're willing to entertain this as a possibility.

**Comment by biilmann** [comment]
Our plan with YARN is to use it instead of npm install whenever we detect a `yarn.lock` file

**Comment by hhsnopek** [comment]
Ayye! This added a couple days ago in 449895f9ca2de55a0babd03bd6617a3a55840fc1 😄
