### ISSUE TITLE
Print a warning message when `NODE_ENV` is `production`

### ISSUE THREAD

**Issue by ehmicky** [netlify/build-image#575]
When `NODE_ENV` is `production`, `devDependencies` are not installed.
This can lead to situations where the build fails due to missing dependencies, which results in bug reports and support tickets.

Conceptually, it seems to me builds should never use `NODE_ENV="production"`. Are there any legitimate use cases for this? It seems like most builds would need development dependencies and are technically part of the development flow, not production.

What are your thoughts on printing a warning message when `NODE_ENV` is `production`, warning that development dependencies will not be installed and might be missing?

cc @kaganjd

**Comment by ehmicky** [comment]
Some good points made by @erquhart:

> Setting NODE_ENV to "production" is a pretty standard pattern, even for build tools used for front end development - for example, unless configured otherwise, Webpack will key off of this value to optimize builds. create-react-app touches on it as well: https://create-react-app.dev/docs/adding-custom-environment-variables

**Comment by kaganjd** [comment]
This would be awesome- has definitely been a source of confusion for customers. Let me know if there's anything I can help with.

Also linking some related issues:
- https://github.com/netlify/cli/issues/473#issuecomment-832848253 (NODE_ENV default in functions is undefined if I'm reading this correctly)
- https://answers.netlify.com/t/support-guide-using-environment-variables-on-netlify-correctly/267/81?u=jen (Gatsby overrides NODE_ENV)

and just in time to add to this issue, an enterprise customer sharing that they add this log themselves in order to debug: https://netlify.zendesk.com/agent/tickets/58438
