### ISSUE TITLE
Ubuntu Focal 20.04 beta: gem command not found

### ISSUE THREAD

**Issue by peaceiris** [netlify/build-image#599]
To new visitors, here is a workaround. https://github.com/netlify/build-image/issues/599#issuecomment-922429047

---

The build image Ubuntu Focal 20.04 (Beta) fails in initialization with the error `gem: command not found`.

Log: https://app.netlify.com/sites/mkdocs-material/deploys/60f6b61ec8f08bcff3aab104

```txt
...
8:40:27 PM: Using /opt/buildhome/.rvm/gems/ruby-2.3.6
8:40:27 PM: Warning! Executable 'ruby' missing, something went wrong with this ruby installation!
8:40:27 PM: Warning! Executable 'gem' missing, something went wrong with this ruby installation!
8:40:27 PM: Warning! Executable 'irb' missing, something went wrong with this ruby installation!
8:40:27 PM: Using ruby version 2.3.6
8:40:27 PM: /opt/buildhome/.rvm/scripts/override_gem: line 19: gem: command not found
8:40:27 PM: Error installing bundler
8:40:27 PM: Build was terminated: Build script returned non-zero exit code: 1
8:40:27 PM: Creating deploy upload records
8:40:27 PM: Failing build: Failed to build site
8:40:28 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
8:40:28 PM: Finished processing build request in 11.612451824s
```

**Comment by julienw** [comment]
~~I've encountered this as well. The weird thing is that running the build locally works fine.~~
~~Locally I used the xenial image actually :man_facepalming: ~~
I tried again locally, this time with the focal image, and this error doesn't appear locally. Was that fixed recently but not deployed yet?

**Comment by valentine** [comment]
I'm having the same problem on a deploy that I've switched from 14.04. 16.04 works for now.

**Comment by peaceiris** [comment]
This error still exists today. To use Python 3.8, I am using the Ubuntu Focal 20.04 beta.

cf. https://github.com/netlify/build-image/issues/431#issuecomment-838996967

**Comment by domenkozar** [comment]
Doesn't this mean that 20.04 never works?

**Comment by peaceiris** [comment]
Ubuntu Focal 20.04 never works.

**Comment by JGAntunes** [comment]
Hey folks 👋

Thanks for raising this and apologies for taking a while to come back to you. The problem at hand is related with the way old sites have some of their language and runtime versions pinned by default, resulting in a sub-optimal experience when the underlying image is changed, given these runtimes/language versions are no longer supported in that new environment. We're working on addressing these ruby `2.3.6` incompatibility issues for anyone that is currently upgrading to focal. Meanwhile though, if you want to upgrade you can either re-link your repo or set a higher `RUBY_VERSION` (see [here](https://answers.netlify.com/t/please-read-end-of-support-for-trusty-build-image-everything-you-need-to-know/39004#how-can-i-make-my-site-work-with-the-new-image-6), under the point `3.` on how to perform either).

**Comment by danielcompton** [comment]
@JGAntunes where can we see the version pinning for our builds? I don’t have any environment variables set apart from the Hugo version and would have expected to get the latest version in the image?

**Comment by peaceiris** [comment]
I have pinned the `RUBY_VERSION` in the `netlify.toml`. It works well now. Thanks @JGAntunes 

```toml
[build.environment]
  RUBY_VERSION = "2.7.4"
```

https://github.com/peaceiris/mkdocs-material-boilerplate/commit/50380194209ca3054db7b19edd7e54b72d6f0c0f

**Comment by kaganjd** [comment]
Howdy from Netlify Support 👋 To mitigate this issue for folks going forward, we've shipped an update to automatically set the RUBY_VERSION to 2.7.2 when you upgrade to Focal and we detect that an old version of Ruby is pinned (lower than 2.4)

**Comment by danielcompton** [comment]
@kaganjd how would we know if an old version of Ruby is pinned? Where do we see that in our Netlify config?

**Comment by kaganjd** [comment]
@danielcompton it'll be in the deploy logs of the site. This would have been the default version in the build image when you first built the site, so if your site first built from Trusty, that version would be listed here: https://github.com/netlify/build-image/blob/trusty/included_software.md. We're working on surfacing more helpful build log messages when a language version is selected due to our default pinning!

**Comment by JGAntunes** [comment]
Apologies @danielcompton, I've been off for a while. As @kaganjd mentioned we're working on making it clearer when a default language version is selected for you. As of right now the only way of knowing which version you're using is via the build logs (something [like this example](https://app.netlify.com/sites/monorepo-blog-1-yarn/deploys/6138d67af13c8c12908c0a88#L44)).

I'm gonna go ahead and close this issue, as anyone that would be affected by this due to default version pinning should see their version automatically switched once they move to `focal`. Let us know if that is not the case 👍
