### ISSUE TITLE
Focal Failed to Fetch Dependencies Cache for Existing Project

### ISSUE THREAD

**Issue by jonioni** [netlify/build-image#688]
We recently updated the build image from Xenial to Focal in the dashboard for an old project. However the deployment log always shows "Failed to fetch cache, continuing with build", no matter it's directly deploy or "clear cache and deploy" and even if all previous deploys with the new build image have succeeded:

```bash
5:56:48 PM: Build ready to start
5:56:50 PM: build-image version: 7e10faf349e7a42e522e4b38297aec45774c71a6 (focal)
5:56:50 PM: build-image tag: v4.4.1
5:56:50 PM: buildbot version: ff6c11880c8fecb7862462f6de6c2903fbb80f54
5:56:50 PM: Fetching cached dependencies
5:56:50 PM: Failed to fetch cache, continuing with build
5:56:50 PM: Starting to prepare the repo for build
5:56:51 PM: No cached dependencies found. Cloning fresh repo
```

It's exceedingly time consuming to refetch all dependencies at each deploy.

**Comment by nolessafool** [comment]
Heya @jonioni , our Support team can help debug - that seems specific to your build and I bet we can solve it without code change.  Mind posting your question in the helpdesk if you're a Pro or higher customer (email support@netlify.com from your netlify login email as shown at https://app.netlify.com/user/settings) or in the forums otherwise (https://answers.netlify.com)?  There our Support engineers should be able to help you get things rolling smoother.
