### ISSUE TITLE
Upgrade default version of yarn

### ISSUE THREAD

**Issue by pixelastic** [netlify/build-image#97]
Hello,

The current image uses the yarn v0.18.1, while the current stable version is v1.2.1. This specific old yarn version has an issue with the dependency tree (just like old npm versions) where some dependencies are not installed when doing a `yarn install` in specific configurations.

I'm experiencing this issue in my Netlify build (both on the hosted version and by running the image myself) that starting `webpack` will yield the following errors:

```
6:31:11 PM: + webpack --config webpack.prod.babel.js --progress
6:31:11 PM: module.js:491
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/build/.yarn_cache/npm-webpack-3.5.5-3226f09fc8b3e435ff781e7af34f82b68b26996c/bin/webpack.js:16:13)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

Forcing yarn to v1.2.1 (by editing the `run-build.sh`) actually builds my website correctly, with all dependencies correctly installed. 

I haven't found a way to set this value from `netlify.toml`, it seems I should be able to pass `YARN_VERSION`, but I can't find documentation on the syntax (should it be in `[build]`? in a specific `[context]`?). In any event, I think updating the default version of yarn can only be beneficial.

**Comment by fool** [comment]
We know our default yarn is old and we'll probably get it updated soon - but that will only automatically take effect for sites created after the change (older sites will stay "pinned" to that old version so we don't surprise people who rely on it in their working builds).

So - you've guessed right that you'll want to specify and that is the best way, to set YARN_VERSION.  Check out https://www.netlify.com/docs/build-settings/ for all the things you can set that will affect the build!

You can set `YARN_VERSION`  in many ways.  If you use netlify.toml, I guess you'd want it to be global which would be `[build.environment]` (rather than setting separately for `[context.(production|branch-deploy|deploy-preview)]`).  You could also use the Build Environment Variables in your build & deploy settings - second section down under the repo specification - and that will take effect for every build with or without netlify.toml.

If that doesn't work - best to open a support ticket since this isn't really a bug :)

**Comment by pixelastic** [comment]
Thanks for the update,

I had read the linked page already, as well as many other pages of the documentation, and even if it could tell me that the option I needed was `YARN_VERSION`, I could not find what the section name in the `netlify.toml` file was supposed to be. Maybe that's something that should be added to this documentation page.

My build is still not working (still an issue with dependencies), but I'm going to ask support directly now :)

Thanks again for the informations
